### PR TITLE
:art: 修復無法移除 GaaS 觀察名單的問題。

### LINKED ISSUE #140: GaaS 觀察名單無法移除已經存在的成員
**Bug report title：**
GaaS 觀察名單無法移除已經存在的成員
**Describe the bug：**

/gaas unobserved 無法作用

**File on：**
UnobservedMemberLister

**Steps to Reproduce：**

**Screenshots：**

image

### PR DESCRIPTION
**Pull request by frankvicky**
## Why need this change? / Root cause: 
- 修復無法移除 GaaS 觀察名單的問題。
## Changes made:
- GaaS, Main
## Test Scope / Change impact:
- GaaS, Main

resolved #140 

### Summary by OpenAI

Release Notes:
- New Feature: Added functionality to publish a message in the GaaS conversation channel when a member is removed from the observed list.
- Bug fix: Fixed an issue where GaaS observation list could not be removed.
- Refactor: Modified `removeRoleFromRecord` function to publish a removal message before removing the role from the member.
- Chore: Minor code formatting changes and dependency injection configuration updates.

> "Code changes abound,
> Bugs fixed, features found,
> With each commit we grow,
> Utopia's greatness on show."

### CODE REVIEW

File: gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/ExpiredMemberListener.kt [hunk 1]
```diff
@@ -52,9 +59,17 @@ class ExpiredMemberListener(
     }
 
     private fun removeRoleFromRecord(guild: Guild, record: ObservedMemberRecord, role: Role) {
-        guild.removeRoleFromMember(UserSnowflake.fromId(record.id), role).queue {
+        val userSnowflake = UserSnowflake.fromId(record.id)
```
Comment (Wally5077) [inline gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/ExpiredMemberListener.kt:62]: `userId`

**Review by Wally5077 — CHANGES_REQUESTED** [review]
Review done.

**Review by Wally5077 — APPROVED** [review]
LGTM
