### PR TITLE
:bug: Fix the bug in asking leave function.

### LINKED ISSUE #134: 遊戲微服務請假按鈕只能一個人使用
**Bug report title：**
遊戲微服務請假按鈕只能一個人使用

**Describe the bug：**

遊戲微服務計畫請假功能在第一個使用之後，其他人使用會出現錯誤

**File on：**
PersonalLeave.kt

**Steps to Reproduce：**

1. 建立遊戲微服務讀書會活動
2. 請假並提交
3. 再次請假

**Screenshots：**

image

### PR DESCRIPTION
**Pull request by frankvicky**
## Why need this change? / Root cause: 
- Fix the bug in asking leave function.
## Changes made:
- GaaS Module
## Test Scope / Change impact:
- none.

resolved #134 

### Summary by OpenAI

**Release Notes**
- Bug fix: Fixed a bug in `createLeaveRecordFile()` and `createParticipantsStatsFile()` functions by checking if the file already exists before creating it.
- New Feature: Added two extension functions to the `Path` class for checking if a file exists and creating a file with a given filename in the directory represented by the `Path` object.
- Chore: Imported new extension functions and replaced a JDA reply callback with an extension function.
- Chore: Added an import statement for `addRequiredOption`.
- Chore: Changed the package name from `tw.waterballsa.utopia.gaas` to `tw.waterballsa.utopia.gaas.extensions`.

> Changes abound, 
> Bugs are found and fixed, 
> Extensions added, 
> Code structure mixed.

### CODE REVIEW

File: gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/PersonalLeave.kt [hunk 1]
```diff
@@ -110,9 +111,10 @@ class PersonalLeave(private val properties: WsaDiscordProperties): UtopiaListene
...
     private fun ScheduledEvent.isGaaSEvent(): Boolean = eventNameKeywords.all { it in name }
 
-    private fun createLeaveRecordFile(): Path =
-        Path(DATABASE_DIRECTORY)
+    private fun createLeaveRecordFile(): Path {
+        val path = Path(DATABASE_DIRECTORY)
             .createDirectories()
             .resolve("$DATABASE_FILENAME_PREFIX-${LocalDate.now()}.db")
-            .createFile()
+        return if (path.exists()) path else path.createFile()
```
Comment (Wally5077) [inline gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/PersonalLeave.kt:118]: NIT：這可以改成擴充方法變「createFileIfNotExists」嗎

File: gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/RecordingParticipants.kt [hunk 2]
```diff
@@ -128,8 +129,9 @@ private fun writeParticipantsIntoFile(newContent: Collection<String>, filePath:
...
 
-private fun createParticipantsStatsFile(): Path =
-    Path(DATABASE_DIRECTORY)
+private fun createParticipantsStatsFile(): Path {
+    val path = Path(DATABASE_DIRECTORY)
         .createDirectories()
         .resolve("$DATABASE_FILENAME_PREFIX-${LocalDate.now()}.db")
-        .createFile()
+    return if (path.exists()) path else path.createFile()
+}
```
Comment (Wally5077) [inline gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/RecordingParticipants.kt:137]: NIT：似乎和另一個函數邏輯重複了，看要不要萃取成一個 Path 的擴充方法做完這些事情？

**Review by Wally5077 — CHANGES_REQUESTED** [review]
Review done.

**Review by Wally5077 — APPROVED** [review]
LGTM
